### ISSUE TITLE
REQ: Maintaining layout with lengthy artboards

### ISSUE THREAD

**Issue by iamhenry** [elihorne/smartboards#5]
So I use your plugin on a daily bases - literally. Thanks for the all the effort in making this. 

I do wish you can maintain the same layout consistency regardless of the length of the artboard. Usually when I run the script the normal size artboards go underneath the large artboard. So, would it be possible to have a dynamic set of artboard in length/width while maintaining the padding across the page? 

Attached is a screenshot of what I'm referring to.

Thanks!

![screen shot 2015-06-25 at 2 48 08 pm](https://cloud.githubusercontent.com/assets/923439/8366359/3e2d1408-1b49-11e5-8dc3-9bd13eb42958.png)

**Comment by elihorne** [comment]
It sounds like you want "organize artboards" (name and padding) and preserve rows for items sharing the same y-axis.

Am I understanding correctly?

**Comment by iamhenry** [comment]
Yes, sound right!

**Comment by iamhenry** [comment]
Would it also be possible to have it maintain its layout if the artboard in that row is wider than the rest?
<img width="901" alt="screen shot 2015-07-28 at 1 38 15 pm" src="https://cloud.githubusercontent.com/assets/923439/8943138/14915dbc-352e-11e5-977e-bf7bd7fc2dc9.png">

**Comment by elihorne** [comment]
Sorry for the radio silence. I'm still chipping away at this request,
although I saw this plugin yesterday which seems to do almost 100% of what
mine does.  Maybe a good interim solution?

https://github.com/romannurik/Sketch-ArtboardTricks/

**Comment by iamhenry** [comment]
That looks like it could work. I'm going to check it out. Thanks for sharing!

**Comment by elihorne** [comment]
I just updated the plugin this week, and it now supports mixed artboard sizes. If you are still using smart boards, give it a try :)
