### ISSUE TITLE
Custom name

### ISSUE THREAD

**Issue by n8mills** [elihorne/smartboards#7]
when uploading to sites like invision artboards mix all together because of naming structure e.g. A00_FORUM, A00_LOGIN

option to have the custom name appear at the start e.g. FORUM_A00, FORUM_A01, LOGIN_A00, LOGIN_A01.

would be a major help

**Comment by elihorne** [comment]
I'm closing this one out because I just don't think I'm going to get around to it. The main purpose of the naming is to alphabetize the export. My guess would be that there are other naming plugins that will do this. 

Thanks for submitting the issue.
